package com.stu.edu.vn.backend.common.exception;

import org.springframework.http.HttpStatus;

/**
 * Mã lỗi nghiệp vụ dùng chung để response lỗi nhất quán giữa các module.
 */
public enum ErrorCode {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "Dữ liệu không hợp lệ"),
    INVALID_IDENTIFIER(HttpStatus.BAD_REQUEST, "Email không hợp lệ"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "Email hoặc mật khẩu không đúng"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "Refresh Token không hợp lệ"),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Refresh Token đã hết hạn"),
    REFRESH_TOKEN_REVOKED(HttpStatus.UNAUTHORIZED, "Refresh Token đã bị thu hồi"),
    AUTH_REFRESH_TOKEN_ROTATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể làm mới phiên đăng nhập, vui lòng thử lại sau"),
    AUTH_LOGOUT_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đăng xuất, vui lòng thử lại sau"),
    AUTH_GOOGLE_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST, "Google ID Token không được để trống"),
    AUTH_GOOGLE_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token không hợp lệ"),
    AUTH_GOOGLE_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Google ID Token đã hết hạn"),
    AUTH_GOOGLE_AUDIENCE_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token không dành cho ứng dụng này"),
    AUTH_GOOGLE_ISSUER_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token có issuer không hợp lệ"),
    AUTH_GOOGLE_SUBJECT_MISSING(HttpStatus.UNAUTHORIZED, "Google ID Token thiếu định danh tài khoản"),
    AUTH_GOOGLE_EMAIL_MISSING(HttpStatus.UNPROCESSABLE_ENTITY, "Tài khoản Google không cung cấp email"),
    AUTH_GOOGLE_EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "Email Google chưa được xác minh"),
    AUTH_GOOGLE_PROVIDER_CONFLICT(HttpStatus.CONFLICT, "Danh tính Google đã thuộc tài khoản khác"),
    AUTH_SOCIAL_ACCOUNT_CONFLICT(HttpStatus.CONFLICT, "Cần xác minh tài khoản hiện có trước khi tiếp tục"),
    AUTH_SOCIAL_PENDING_CONFLICT(HttpStatus.CONFLICT, "Đăng ký local đang chờ cần được xử lý trước"),
    AUTH_SOCIAL_CHALLENGE_INVALID(HttpStatus.UNAUTHORIZED, "Social conflict token không hợp lệ"),
    AUTH_SOCIAL_CHALLENGE_EXPIRED(HttpStatus.GONE, "Social conflict token đã hết hạn"),
    AUTH_SOCIAL_CHALLENGE_ALREADY_USED(HttpStatus.CONFLICT, "Social conflict token đã được sử dụng"),
    AUTH_SOCIAL_CHALLENGE_CANCELLED(HttpStatus.CONFLICT, "Social conflict token đã bị hủy"),
    AUTH_SOCIAL_CHALLENGE_ACTION_INVALID(HttpStatus.BAD_REQUEST, "Hành động không phù hợp với social conflict"),
    AUTH_SOCIAL_PROVIDER_ALREADY_LINKED(HttpStatus.CONFLICT, "Danh tính social đã thuộc tài khoản khác"),
    AUTH_METHOD_ALREADY_LINKED(HttpStatus.CONFLICT, "Phương thức đăng nhập đã được liên kết"),
    AUTH_METHOD_LINK_ALREADY_PENDING(HttpStatus.CONFLICT, "Yêu cầu liên kết đang chờ xác minh"),
    AUTH_METHOD_LINK_CHALLENGE_INVALID(HttpStatus.UNAUTHORIZED, "Link challenge không hợp lệ"),
    AUTH_METHOD_LINK_CHALLENGE_EXPIRED(HttpStatus.GONE, "Link challenge đã hết hạn"),
    AUTH_METHOD_LINK_CHALLENGE_ALREADY_USED(HttpStatus.CONFLICT, "Link challenge đã được sử dụng"),
    AUTH_METHOD_LINK_OTP_INVALID(HttpStatus.BAD_REQUEST, "OTP liên kết không hợp lệ"),
    AUTH_METHOD_LINK_OTP_EXPIRED(HttpStatus.GONE, "OTP liên kết đã hết hạn"),
    AUTH_METHOD_LINK_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "OTP liên kết đã vượt số lần thử"),
    AUTH_EMAIL_ALREADY_IN_USE(HttpStatus.CONFLICT, "Email không thể được liên kết"),
    AUTH_PROVIDER_ALREADY_LINKED(HttpStatus.CONFLICT, "Provider đã thuộc tài khoản khác"),
    AUTH_PROVIDER_LINK_CONFLICT(HttpStatus.CONFLICT, "Không thể liên kết provider này"),
    AUTH_METHOD_NOT_LINKED(HttpStatus.CONFLICT, "Phương thức đăng nhập chưa được liên kết"),
    AUTH_LAST_LOGIN_METHOD_CANNOT_BE_REMOVED(HttpStatus.CONFLICT, "Không thể gỡ phương thức đăng nhập cuối cùng"),
    AUTH_METHOD_UNLINK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể gỡ phương thức đăng nhập"),
    AUTH_REAUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, "Cần xác thực lại trước khi tiếp tục"),
    AUTH_REAUTHENTICATION_INVALID(HttpStatus.UNAUTHORIZED, "Token xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_EXPIRED(HttpStatus.GONE, "Token xác thực lại đã hết hạn"),
    AUTH_REAUTHENTICATION_ALREADY_USED(HttpStatus.CONFLICT, "Token xác thực lại đã được sử dụng"),
    AUTH_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "Quá nhiều yêu cầu xác thực, vui lòng thử lại sau"),
    AUTH_REAUTHENTICATION_METHOD_INVALID(HttpStatus.BAD_REQUEST, "Phương thức xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_METHOD_UNAVAILABLE(HttpStatus.FORBIDDEN, "Phương thức xác thực lại chưa khả dụng"),
    AUTH_REAUTHENTICATION_CREDENTIAL_INVALID(HttpStatus.UNAUTHORIZED, "Bằng chứng xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_PURPOSE_INVALID(HttpStatus.BAD_REQUEST, "Mục đích xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_TARGET_INVALID(HttpStatus.BAD_REQUEST, "Phương thức đích không hợp lệ"),
    AUTH_REAUTHENTICATION_PROVIDER_NOT_LINKED(HttpStatus.FORBIDDEN, "Provider chưa liên kết với tài khoản hiện tại"),
    AUTH_REAUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất xác thực lại"),
    AUTH_GOOGLE_AUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng nhập Google"),
    AUTH_FACEBOOK_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST, "Facebook Access Token không được để trống"),
    AUTH_FACEBOOK_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Facebook Access Token không hợp lệ"),
    AUTH_FACEBOOK_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Facebook Access Token đã hết hạn"),
    AUTH_FACEBOOK_APP_INVALID(HttpStatus.UNAUTHORIZED, "Facebook Access Token không dành cho ứng dụng này"),
    AUTH_FACEBOOK_USER_ID_MISSING(HttpStatus.UNAUTHORIZED, "Facebook Access Token thiếu định danh tài khoản"),
    AUTH_FACEBOOK_EMAIL_MISSING(HttpStatus.UNPROCESSABLE_ENTITY, "Tài khoản Facebook không cung cấp email"),
    AUTH_FACEBOOK_PROVIDER_CONFLICT(HttpStatus.CONFLICT, "Danh tính Facebook đã thuộc tài khoản khác"),
    AUTH_FACEBOOK_UNAVAILABLE(HttpStatus.BAD_GATEWAY, "Facebook tạm thời không khả dụng"),
    AUTH_FACEBOOK_AUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng nhập Facebook"),
    PASSWORD_CONFIRMATION_NOT_MATCH(HttpStatus.BAD_REQUEST, "Xác nhận mật khẩu không khớp"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "Email đã được sử dụng"),
    REGISTER_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng ký, vui lòng thử lại sau"),
    AUTH_IDENTIFIER_INVALID(HttpStatus.BAD_REQUEST, "Email không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_START_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể bắt đầu khôi phục mật khẩu"),
    AUTH_PASSWORD_RECOVERY_FLOW_INVALID(HttpStatus.UNAUTHORIZED, "Phiên khôi phục mật khẩu không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_FLOW_EXPIRED(HttpStatus.GONE, "Phiên khôi phục mật khẩu đã hết hạn"),
    AUTH_PASSWORD_RECOVERY_FLOW_ALREADY_USED(HttpStatus.CONFLICT, "Phiên khôi phục mật khẩu đã được sử dụng"),
    AUTH_PASSWORD_RECOVERY_OTP_INVALID(HttpStatus.BAD_REQUEST, "Mã xác minh không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_OTP_EXPIRED(HttpStatus.GONE, "Mã xác minh đã hết hạn"),
    AUTH_PASSWORD_RECOVERY_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "Mã xác minh đã vượt số lần thử"),
    AUTH_PASSWORD_RECOVERY_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS, "Chưa đến thời điểm được gửi lại mã"),
    AUTH_PASSWORD_RESET_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Phiên đặt lại mật khẩu không hợp lệ"),
    AUTH_PASSWORD_RESET_TOKEN_EXPIRED(HttpStatus.GONE, "Phiên đặt lại mật khẩu đã hết hạn"),
    AUTH_PASSWORD_RESET_TOKEN_USED(HttpStatus.CONFLICT, "Phiên đặt lại mật khẩu đã được sử dụng"),
    AUTH_PASSWORD_MUST_BE_DIFFERENT(HttpStatus.BAD_REQUEST, "Mật khẩu mới phải khác mật khẩu hiện tại"),
    AUTH_PASSWORD_CONFIRMATION_MISMATCH(HttpStatus.BAD_REQUEST, "Xác nhận mật khẩu không khớp"),
    AUTH_PASSWORD_POLICY_VIOLATION(HttpStatus.BAD_REQUEST, "Mật khẩu không đáp ứng chính sách bảo mật"),
    AUTH_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "Email đã thuộc một tài khoản"),
    AUTH_REGISTRATION_ALREADY_PENDING(HttpStatus.CONFLICT, "Đăng ký cho định danh này đang chờ xác minh"),
    AUTH_OTP_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY, "Không thể gửi OTP, vui lòng thử gửi lại sau"),
    AUTH_REGISTRATION_START_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể bắt đầu đăng ký, vui lòng thử lại sau"),
    AUTH_REGISTRATION_FLOW_INVALID(HttpStatus.UNAUTHORIZED, "Registration flow token không hợp lệ"),
    AUTH_REGISTRATION_NOT_PENDING(HttpStatus.CONFLICT, "Đăng ký không còn ở trạng thái chờ xác minh"),
    AUTH_REGISTRATION_EXPIRED(HttpStatus.GONE, "Đăng ký đã hết hạn"),
    AUTH_REGISTRATION_ALREADY_COMPLETED(HttpStatus.CONFLICT, "Đăng ký đã được hoàn tất"),
    AUTH_REGISTRATION_CANCELLED(HttpStatus.CONFLICT, "Đăng ký đã bị hủy"),
    AUTH_OTP_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS, "Chưa đến thời điểm được gửi lại OTP"),
    AUTH_REGISTRATION_STATUS_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đọc trạng thái đăng ký"),
    AUTH_REGISTRATION_CANCEL_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hủy đăng ký"),
    AUTH_OTP_INVALID(HttpStatus.BAD_REQUEST, "Mã OTP không hợp lệ"),
    AUTH_OTP_EXPIRED(HttpStatus.GONE, "Mã OTP đã hết hạn"),
    AUTH_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "Mã OTP hiện tại đã vượt quá số lần thử"),
    AUTH_ACCOUNT_CREATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể tạo tài khoản, vui lòng thử lại sau"),
    AUTH_IDENTIFIER_NOT_VERIFIED(HttpStatus.FORBIDDEN, "Email chưa được xác minh"),
    AUTH_PASSWORD_LOGIN_NOT_AVAILABLE(HttpStatus.FORBIDDEN, "Tài khoản chưa hỗ trợ đăng nhập bằng mật khẩu"),
    AUTH_REFRESH_TOKEN_CREATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể tạo phiên đăng nhập, vui lòng thử lại sau"),
    AUTH_LOGIN_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đăng nhập, vui lòng thử lại sau"),
    PROFILE_NOT_COMPLETED(HttpStatus.FORBIDDEN, "Bạn cần hoàn tất hồ sơ trước khi sử dụng chức năng này"),
    PROFILE_ALREADY_COMPLETED(HttpStatus.CONFLICT, "Hồ sơ ban đầu đã được hoàn tất"),
    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy hồ sơ người dùng"),
    INVALID_DISPLAY_NAME(HttpStatus.BAD_REQUEST, "Tên hiển thị phải từ 2 đến 100 ký tự"),
    INVALID_DATE_OF_BIRTH(HttpStatus.BAD_REQUEST, "Ngày sinh không hợp lệ"),
    USER_UNDER_MINIMUM_AGE(HttpStatus.BAD_REQUEST, "Người dùng phải đủ 18 tuổi"),
    BIO_TOO_LONG(HttpStatus.BAD_REQUEST, "Giới thiệu cá nhân không được vượt quá 500 ký tự"),
    AVATAR_FILE_REQUIRED(HttpStatus.BAD_REQUEST, "Vui lòng chọn ảnh đại diện"),
    AVATAR_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "Ảnh đại diện không được vượt quá 10 MB"),
    AVATAR_FILE_TYPE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Định dạng ảnh đại diện không được hỗ trợ"),
    AVATAR_MIME_TYPE_INVALID(HttpStatus.BAD_REQUEST, "Nội dung tệp ảnh đại diện không hợp lệ"),
    AVATAR_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tải ảnh đại diện lên hệ thống"),
    AVATAR_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể xóa ảnh đại diện"),
    CLOUDINARY_CONFIGURATION_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, "Cấu hình lưu trữ ảnh chưa hợp lệ"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "Bạn cần đăng nhập để tiếp tục"),
    INVALID_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED, "Access Token không hợp lệ"),
    ACCESS_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Access Token đã hết hạn"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy người dùng"),
    USER_BLOCKED(HttpStatus.FORBIDDEN, "Tài khoản đã bị khóa"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "Bạn không có quyền thực hiện thao tác này"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy dữ liệu"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Hệ thống đang gặp lỗi, vui lòng thử lại sau");

    private final HttpStatus httpStatus;
    private final String defaultMessage;

    ErrorCode(HttpStatus httpStatus, String defaultMessage) {
        this.httpStatus = httpStatus;
        this.defaultMessage = defaultMessage;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }

    public String getDefaultMessage() {
        return defaultMessage;
    }
}
