package com.stu.edu.vn.backend.common.exception;

import org.springframework.http.HttpStatus;

/**
 * Mã lỗi nghiệp vụ dùng chung để response lỗi nhất quán giữa các module.
 */
public enum ErrorCode {
    ANALYTICS_MONTH_INVALID(HttpStatus.BAD_REQUEST, "Tháng thống kê phải có định dạng yyyy-MM"),
    ANALYTICS_MONTH_RANGE_INVALID(HttpStatus.BAD_REQUEST, "Tháng bắt đầu không được sau tháng kết thúc"),
    ANALYTICS_FUTURE_MONTH(HttpStatus.BAD_REQUEST, "Tháng kết thúc không được nằm trong tương lai"),
    ANALYTICS_MONTH_RANGE_TOO_LARGE(HttpStatus.BAD_REQUEST, "Khoảng thống kê không được vượt quá 24 tháng"),
    ANALYTICS_INACTIVE_DAYS_INVALID(HttpStatus.BAD_REQUEST, "inactiveDays phải nằm trong khoảng từ 1 đến 365"),
    HASHTAG_SUGGESTION_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa gợi ý hashtag không được vượt quá 100 ký tự"),
    ADMIN_ACTION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy lịch sử thao tác quản trị"),
    ADMIN_MODERATION_CASE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy hồ sơ kiểm duyệt"),
    ADMIN_MODERATION_CASE_ALREADY_RESOLVED(HttpStatus.CONFLICT, "Hồ sơ kiểm duyệt đã được giải quyết"),
    ADMIN_MODERATION_CASE_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa hồ sơ kiểm duyệt không được vượt quá 100 ký tự"),
    ADMIN_MODERATION_CASE_RESOLUTION_NOTE_TOO_LONG(HttpStatus.BAD_REQUEST, "Kết luận xử lý hồ sơ kiểm duyệt không được vượt quá 1000 ký tự"),
    ADMIN_REPORT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy báo cáo cần quản lý"),
    ADMIN_REPORT_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa báo cáo quản trị không được vượt quá 100 ký tự"),
    ADMIN_REPORT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "Báo cáo đã được xử lý"),
    ADMIN_REPORT_RESOLUTION_NOTE_REQUIRED(HttpStatus.BAD_REQUEST, "Ghi chú xử lý báo cáo là bắt buộc"),
    ADMIN_REPORT_RESOLUTION_NOTE_TOO_LONG(HttpStatus.BAD_REQUEST, "Ghi chú xử lý báo cáo không được vượt quá 500 ký tự"),
    ADMIN_REPORT_HIDE_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "Lý do ẩn bài viết là bắt buộc"),
    ADMIN_REPORT_HIDE_REASON_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Không được gửi lý do ẩn khi không yêu cầu ẩn bài viết"),
    ADMIN_POST_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bài viết cần quản lý"),
    ADMIN_POST_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa bài viết quản trị không được vượt quá 100 ký tự"),
    ADMIN_POST_ALREADY_HIDDEN(HttpStatus.CONFLICT, "Bài viết đã bị ẩn"),
    ADMIN_POST_ALREADY_PUBLISHED(HttpStatus.CONFLICT, "Bài viết đang ở trạng thái công khai"),
    ADMIN_POST_DELETED_ACTION_FORBIDDEN(HttpStatus.CONFLICT, "Không thể thay đổi bài viết đã bị xóa"),
    ADMIN_POST_HIDE_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "Lý do ẩn bài viết là bắt buộc"),
    ADMIN_USER_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy tài khoản người dùng cần quản lý"),
    ADMIN_USER_MANAGEMENT_FORBIDDEN(HttpStatus.FORBIDDEN, "Không được phép quản lý tài khoản ADMIN"),
    ADMIN_SELF_ACTION_FORBIDDEN(HttpStatus.FORBIDDEN, "ADMIN không được phép thay đổi trạng thái tài khoản của chính mình"),
    ADMIN_USER_ALREADY_BLOCKED(HttpStatus.CONFLICT, "Tài khoản người dùng đã bị khóa"),
    ADMIN_USER_ALREADY_ACTIVE(HttpStatus.CONFLICT, "Tài khoản người dùng đang hoạt động"),
    ADMIN_BLOCK_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "Lý do khóa tài khoản là bắt buộc"),
    SEARCH_HASHTAG_INVALID(HttpStatus.BAD_REQUEST, "Hashtag tìm kiếm không hợp lệ"),
    SEARCH_KEYWORD_REQUIRED(HttpStatus.BAD_REQUEST, "Từ khóa tìm kiếm không được để trống"),
    SEARCH_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa tìm kiếm không được vượt quá 100 ký tự"),
    INVALID_CURSOR(HttpStatus.BAD_REQUEST, "Cursor phân trang không hợp lệ"),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "Dữ liệu không hợp lệ"),
    INVALID_IDENTIFIER(HttpStatus.BAD_REQUEST, "Email không hợp lệ"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "Email hoặc mật khẩu không đúng"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "Refresh Token không hợp lệ"),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Refresh Token đã hết hạn"),
    REFRESH_TOKEN_REVOKED(HttpStatus.UNAUTHORIZED, "Refresh Token đã bị thu hồi"),
    AUTH_REFRESH_TOKEN_ROTATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể làm mới phiên đăng nhập, vui lòng thử lại sau"),
    AUTH_LOGOUT_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đăng xuất, vui lòng thử lại sau"),
    AUTH_GOOGLE_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST, "Google ID Token không được để trống"),
    AUTH_GOOGLE_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token không hợp lệ"),
    AUTH_GOOGLE_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Google ID Token đã hết hạn"),
    AUTH_GOOGLE_AUDIENCE_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token không dành cho ứng dụng này"),
    AUTH_GOOGLE_ISSUER_INVALID(HttpStatus.UNAUTHORIZED, "Google ID Token có issuer không hợp lệ"),
    AUTH_GOOGLE_SUBJECT_MISSING(HttpStatus.UNAUTHORIZED, "Google ID Token thiếu định danh tài khoản"),
    AUTH_GOOGLE_EMAIL_MISSING(HttpStatus.UNPROCESSABLE_ENTITY, "Tài khoản Google không cung cấp email"),
    AUTH_GOOGLE_EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "Email Google chưa được xác minh"),
    AUTH_GOOGLE_PROVIDER_CONFLICT(HttpStatus.CONFLICT, "Danh tính Google đã thuộc tài khoản khác"),
    AUTH_SOCIAL_ACCOUNT_CONFLICT(HttpStatus.CONFLICT, "Cần xác minh tài khoản hiện có trước khi tiếp tục"),
    AUTH_SOCIAL_PENDING_CONFLICT(HttpStatus.CONFLICT, "Đăng ký local đang chờ cần được xử lý trước"),
    AUTH_SOCIAL_CHALLENGE_INVALID(HttpStatus.UNAUTHORIZED, "Social conflict token không hợp lệ"),
    AUTH_SOCIAL_CHALLENGE_EXPIRED(HttpStatus.GONE, "Social conflict token đã hết hạn"),
    AUTH_SOCIAL_CHALLENGE_ALREADY_USED(HttpStatus.CONFLICT, "Social conflict token đã được sử dụng"),
    AUTH_SOCIAL_CHALLENGE_CANCELLED(HttpStatus.CONFLICT, "Social conflict token đã bị hủy"),
    AUTH_SOCIAL_CHALLENGE_ACTION_INVALID(HttpStatus.BAD_REQUEST, "Hành động không phù hợp với social conflict"),
    AUTH_SOCIAL_PROVIDER_ALREADY_LINKED(HttpStatus.CONFLICT, "Danh tính social đã thuộc tài khoản khác"),
    AUTH_METHOD_ALREADY_LINKED(HttpStatus.CONFLICT, "Phương thức đăng nhập đã được liên kết"),
    AUTH_METHOD_LINK_ALREADY_PENDING(HttpStatus.CONFLICT, "Yêu cầu liên kết đang chờ xác minh"),
    AUTH_METHOD_LINK_CHALLENGE_INVALID(HttpStatus.UNAUTHORIZED, "Link challenge không hợp lệ"),
    AUTH_METHOD_LINK_CHALLENGE_EXPIRED(HttpStatus.GONE, "Link challenge đã hết hạn"),
    AUTH_METHOD_LINK_CHALLENGE_ALREADY_USED(HttpStatus.CONFLICT, "Link challenge đã được sử dụng"),
    AUTH_METHOD_LINK_OTP_INVALID(HttpStatus.BAD_REQUEST, "OTP liên kết không hợp lệ"),
    AUTH_METHOD_LINK_OTP_EXPIRED(HttpStatus.GONE, "OTP liên kết đã hết hạn"),
    AUTH_METHOD_LINK_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "OTP liên kết đã vượt số lần thử"),
    AUTH_EMAIL_ALREADY_IN_USE(HttpStatus.CONFLICT, "Email không thể được liên kết"),
    AUTH_PROVIDER_ALREADY_LINKED(HttpStatus.CONFLICT, "Provider đã thuộc tài khoản khác"),
    AUTH_PROVIDER_LINK_CONFLICT(HttpStatus.CONFLICT, "Không thể liên kết provider này"),
    AUTH_METHOD_NOT_LINKED(HttpStatus.CONFLICT, "Phương thức đăng nhập chưa được liên kết"),
    AUTH_LAST_LOGIN_METHOD_CANNOT_BE_REMOVED(HttpStatus.CONFLICT, "Không thể gỡ phương thức đăng nhập cuối cùng"),
    AUTH_METHOD_UNLINK_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể gỡ phương thức đăng nhập"),
    AUTH_REAUTHENTICATION_REQUIRED(HttpStatus.UNAUTHORIZED, "Cần xác thực lại trước khi tiếp tục"),
    AUTH_REAUTHENTICATION_INVALID(HttpStatus.UNAUTHORIZED, "Token xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_EXPIRED(HttpStatus.GONE, "Token xác thực lại đã hết hạn"),
    AUTH_REAUTHENTICATION_ALREADY_USED(HttpStatus.CONFLICT, "Token xác thực lại đã được sử dụng"),
    AUTH_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS, "Quá nhiều yêu cầu xác thực, vui lòng thử lại sau"),
    AUTH_REAUTHENTICATION_METHOD_INVALID(HttpStatus.BAD_REQUEST, "Phương thức xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_METHOD_UNAVAILABLE(HttpStatus.FORBIDDEN, "Phương thức xác thực lại chưa khả dụng"),
    AUTH_REAUTHENTICATION_CREDENTIAL_INVALID(HttpStatus.UNAUTHORIZED, "Bằng chứng xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_PURPOSE_INVALID(HttpStatus.BAD_REQUEST, "Mục đích xác thực lại không hợp lệ"),
    AUTH_REAUTHENTICATION_TARGET_INVALID(HttpStatus.BAD_REQUEST, "Phương thức đích không hợp lệ"),
    AUTH_REAUTHENTICATION_PROVIDER_NOT_LINKED(HttpStatus.FORBIDDEN, "Provider chưa liên kết với tài khoản hiện tại"),
    AUTH_REAUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất xác thực lại"),
    AUTH_GOOGLE_AUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng nhập Google"),
    AUTH_FACEBOOK_TOKEN_REQUIRED(HttpStatus.BAD_REQUEST, "Facebook Access Token không được để trống"),
    AUTH_FACEBOOK_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Facebook Access Token không hợp lệ"),
    AUTH_FACEBOOK_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Facebook Access Token đã hết hạn"),
    AUTH_FACEBOOK_APP_INVALID(HttpStatus.UNAUTHORIZED, "Facebook Access Token không dành cho ứng dụng này"),
    AUTH_FACEBOOK_USER_ID_MISSING(HttpStatus.UNAUTHORIZED, "Facebook Access Token thiếu định danh tài khoản"),
    AUTH_FACEBOOK_EMAIL_MISSING(HttpStatus.UNPROCESSABLE_ENTITY, "Tài khoản Facebook không cung cấp email"),
    AUTH_FACEBOOK_PROVIDER_CONFLICT(HttpStatus.CONFLICT, "Danh tính Facebook đã thuộc tài khoản khác"),
    AUTH_FACEBOOK_UNAVAILABLE(HttpStatus.BAD_GATEWAY, "Facebook tạm thời không khả dụng"),
    AUTH_FACEBOOK_AUTHENTICATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng nhập Facebook"),
    PASSWORD_CONFIRMATION_NOT_MATCH(HttpStatus.BAD_REQUEST, "Xác nhận mật khẩu không khớp"),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "Email đã được sử dụng"),
    REGISTER_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hoàn tất đăng ký, vui lòng thử lại sau"),
    AUTH_IDENTIFIER_INVALID(HttpStatus.BAD_REQUEST, "Email không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_START_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể bắt đầu khôi phục mật khẩu"),
    AUTH_PASSWORD_RECOVERY_FLOW_INVALID(HttpStatus.UNAUTHORIZED, "Phiên khôi phục mật khẩu không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_FLOW_EXPIRED(HttpStatus.GONE, "Phiên khôi phục mật khẩu đã hết hạn"),
    AUTH_PASSWORD_RECOVERY_FLOW_ALREADY_USED(HttpStatus.CONFLICT, "Phiên khôi phục mật khẩu đã được sử dụng"),
    AUTH_PASSWORD_RECOVERY_OTP_INVALID(HttpStatus.BAD_REQUEST, "Mã xác minh không hợp lệ"),
    AUTH_PASSWORD_RECOVERY_OTP_EXPIRED(HttpStatus.GONE, "Mã xác minh đã hết hạn"),
    AUTH_PASSWORD_RECOVERY_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "Mã xác minh đã vượt số lần thử"),
    AUTH_PASSWORD_RECOVERY_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS, "Chưa đến thời điểm được gửi lại mã"),
    AUTH_PASSWORD_RESET_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Phiên đặt lại mật khẩu không hợp lệ"),
    AUTH_PASSWORD_RESET_TOKEN_EXPIRED(HttpStatus.GONE, "Phiên đặt lại mật khẩu đã hết hạn"),
    AUTH_PASSWORD_RESET_TOKEN_USED(HttpStatus.CONFLICT, "Phiên đặt lại mật khẩu đã được sử dụng"),
    AUTH_PASSWORD_MUST_BE_DIFFERENT(HttpStatus.BAD_REQUEST, "Mật khẩu mới phải khác mật khẩu hiện tại"),
    AUTH_PASSWORD_CONFIRMATION_MISMATCH(HttpStatus.BAD_REQUEST, "Xác nhận mật khẩu không khớp"),
    AUTH_PASSWORD_POLICY_VIOLATION(HttpStatus.BAD_REQUEST, "Mật khẩu không đáp ứng chính sách bảo mật"),
    AUTH_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "Email đã thuộc một tài khoản"),
    AUTH_REGISTRATION_ALREADY_PENDING(HttpStatus.CONFLICT, "Đăng ký cho định danh này đang chờ xác minh"),
    AUTH_OTP_DELIVERY_FAILED(HttpStatus.BAD_GATEWAY, "Không thể gửi OTP, vui lòng thử gửi lại sau"),
    AUTH_REGISTRATION_START_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể bắt đầu đăng ký, vui lòng thử lại sau"),
    AUTH_REGISTRATION_FLOW_INVALID(HttpStatus.UNAUTHORIZED, "Registration flow token không hợp lệ"),
    AUTH_REGISTRATION_NOT_PENDING(HttpStatus.CONFLICT, "Đăng ký không còn ở trạng thái chờ xác minh"),
    AUTH_REGISTRATION_EXPIRED(HttpStatus.GONE, "Đăng ký đã hết hạn"),
    AUTH_REGISTRATION_ALREADY_COMPLETED(HttpStatus.CONFLICT, "Đăng ký đã được hoàn tất"),
    AUTH_REGISTRATION_CANCELLED(HttpStatus.CONFLICT, "Đăng ký đã bị hủy"),
    AUTH_OTP_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS, "Chưa đến thời điểm được gửi lại OTP"),
    AUTH_REGISTRATION_STATUS_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đọc trạng thái đăng ký"),
    AUTH_REGISTRATION_CANCEL_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể hủy đăng ký"),
    AUTH_OTP_INVALID(HttpStatus.BAD_REQUEST, "Mã OTP không hợp lệ"),
    AUTH_OTP_EXPIRED(HttpStatus.GONE, "Mã OTP đã hết hạn"),
    AUTH_OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "Mã OTP hiện tại đã vượt quá số lần thử"),
    AUTH_ACCOUNT_CREATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể tạo tài khoản, vui lòng thử lại sau"),
    AUTH_IDENTIFIER_NOT_VERIFIED(HttpStatus.FORBIDDEN, "Email chưa được xác minh"),
    AUTH_PASSWORD_LOGIN_NOT_AVAILABLE(HttpStatus.FORBIDDEN, "Tài khoản chưa hỗ trợ đăng nhập bằng mật khẩu"),
    AUTH_REFRESH_TOKEN_CREATION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể tạo phiên đăng nhập, vui lòng thử lại sau"),
    AUTH_LOGIN_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể đăng nhập, vui lòng thử lại sau"),
    PROFILE_NOT_COMPLETED(HttpStatus.FORBIDDEN, "Bạn cần hoàn tất hồ sơ trước khi sử dụng chức năng này"),
    MESSAGING_NOT_ALLOWED(HttpStatus.FORBIDDEN, "Tài khoản không được phép sử dụng chức năng nhắn tin"),
    CANNOT_MESSAGE_SELF(HttpStatus.BAD_REQUEST, "Bạn không thể nhắn tin cho chính mình"),
    DIRECT_MESSAGE_NOT_ALLOWED(HttpStatus.FORBIDDEN, "Không thể bắt đầu hoặc tiếp tục cuộc trò chuyện này"),
    CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy cuộc trò chuyện"),
    MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy tin nhắn"),
    MESSAGE_CONTENT_REQUIRED(HttpStatus.BAD_REQUEST, "Nội dung tin nhắn không được để trống"),
    MESSAGE_CONTENT_TOO_LONG(HttpStatus.BAD_REQUEST, "Nội dung tin nhắn không được vượt quá 2000 Unicode code point"),
    MESSAGE_IMAGE_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Mỗi tin nhắn chỉ được có tối đa 5 ảnh"),
    MESSAGE_IMAGE_FILE_EMPTY(HttpStatus.BAD_REQUEST, "Ảnh tin nhắn không được để trống"),
    MESSAGE_IMAGE_TOO_LARGE(HttpStatus.BAD_REQUEST, "Mỗi ảnh tin nhắn không được vượt quá 10 MB"),
    MESSAGE_IMAGE_EXTENSION_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Định dạng ảnh tin nhắn không được hỗ trợ"),
    MESSAGE_IMAGE_MIME_TYPE_INVALID(HttpStatus.BAD_REQUEST, "MIME type ảnh tin nhắn không hợp lệ"),
    MESSAGE_IMAGE_SIGNATURE_INVALID(HttpStatus.BAD_REQUEST, "Chữ ký tệp ảnh tin nhắn không hợp lệ"),
    MESSAGE_IMAGE_DECODE_INVALID(HttpStatus.BAD_REQUEST, "Tệp không thể giải mã thành ảnh hợp lệ"),
    MESSAGE_IMAGE_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tải ảnh tin nhắn lên hệ thống lưu trữ"),
    MESSAGE_MEDIA_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể xóa media tin nhắn"),
    MESSAGE_ATTACHMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy ảnh tin nhắn"),
    INVALID_CLIENT_MESSAGE_ID(HttpStatus.BAD_REQUEST, "clientMessageId phải là UUID v4 hợp lệ"),
    IDEMPOTENCY_KEY_REUSED(HttpStatus.CONFLICT, "clientMessageId đã được sử dụng cho nội dung khác"),
    PROFILE_ALREADY_COMPLETED(HttpStatus.CONFLICT, "Hồ sơ ban đầu đã được hoàn tất"),
    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy hồ sơ người dùng"),
    USERNAME_REQUIRED(HttpStatus.BAD_REQUEST, "Username là bắt buộc"),
    USERNAME_INVALID(HttpStatus.BAD_REQUEST,
            "Username phải từ 3 đến 30 ký tự và chỉ gồm chữ thường, số, dấu gạch dưới hoặc dấu chấm"),
    USERNAME_ALREADY_EXISTS(HttpStatus.CONFLICT, "Username đã được sử dụng"),
    USERNAME_RESERVED(HttpStatus.BAD_REQUEST, "Username này được dành riêng cho hệ thống"),
    INVALID_DISPLAY_NAME(HttpStatus.BAD_REQUEST, "Tên hiển thị phải từ 2 đến 100 ký tự"),
    INVALID_DATE_OF_BIRTH(HttpStatus.BAD_REQUEST, "Ngày sinh không hợp lệ"),
    USER_UNDER_MINIMUM_AGE(HttpStatus.BAD_REQUEST, "Người dùng phải đủ 18 tuổi"),
    BIO_TOO_LONG(HttpStatus.BAD_REQUEST, "Giới thiệu cá nhân không được vượt quá 500 ký tự"),
    ACADEMIC_SCHOOL_INVALID(HttpStatus.BAD_REQUEST, "Trường học không tồn tại hoặc không khả dụng"),
    ACADEMIC_FACULTY_INVALID(HttpStatus.BAD_REQUEST, "Khoa không tồn tại hoặc không khả dụng"),
    ACADEMIC_MAJOR_INVALID(HttpStatus.BAD_REQUEST, "Ngành học không tồn tại hoặc không khả dụng"),
    ACADEMIC_FACULTY_SCHOOL_MISMATCH(HttpStatus.BAD_REQUEST, "Khoa không thuộc trường đã chọn"),
    ACADEMIC_MAJOR_FACULTY_MISMATCH(HttpStatus.BAD_REQUEST, "Ngành học không thuộc khoa đã chọn"),
    ACADEMIC_ENTRY_YEAR_INVALID(HttpStatus.BAD_REQUEST, "Năm nhập học phải từ 1900 đến năm hiện tại"),
    ACADEMIC_LIMIT_INVALID(HttpStatus.BAD_REQUEST, "limit phải nằm trong khoảng từ 1 đến 20"),
    ACADEMIC_KEYWORD_TOO_LONG(HttpStatus.BAD_REQUEST, "Từ khóa học thuật không được vượt quá 100 ký tự"),
    INTEREST_INVALID(HttpStatus.BAD_REQUEST, "Sở thích không tồn tại hoặc không khả dụng"),
    INTEREST_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Chỉ được chọn tối đa 10 sở thích"),
    AVATAR_FILE_REQUIRED(HttpStatus.BAD_REQUEST, "Vui lòng chọn ảnh đại diện"),
    AVATAR_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST, "Ảnh đại diện không được vượt quá 10 MB"),
    AVATAR_FILE_TYPE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Định dạng ảnh đại diện không được hỗ trợ"),
    AVATAR_MIME_TYPE_INVALID(HttpStatus.BAD_REQUEST, "Nội dung tệp ảnh đại diện không hợp lệ"),
    AVATAR_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tải ảnh đại diện lên hệ thống"),
    AVATAR_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể xóa ảnh đại diện"),
    POST_CONTENT_OR_IMAGE_REQUIRED(HttpStatus.BAD_REQUEST, "Bài viết phải có nội dung hoặc ít nhất một media"),
    POST_CONTENT_TOO_LONG(HttpStatus.BAD_REQUEST, "Nội dung bài viết không được vượt quá 500 ký tự"),
    POST_IMAGE_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Bài viết chỉ được tải lên tối đa 4 ảnh"),
    POST_IMAGE_FILE_EMPTY(HttpStatus.BAD_REQUEST, "Ảnh bài viết không được để trống"),
    POST_IMAGE_TOO_LARGE(HttpStatus.BAD_REQUEST, "Mỗi ảnh bài viết không được vượt quá 10 MB"),
    POST_IMAGE_EXTENSION_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Định dạng ảnh bài viết không được hỗ trợ"),
    POST_IMAGE_MIME_TYPE_INVALID(HttpStatus.BAD_REQUEST, "MIME type của ảnh bài viết không hợp lệ"),
    POST_IMAGE_SIGNATURE_INVALID(HttpStatus.BAD_REQUEST, "Nội dung tệp ảnh bài viết không hợp lệ"),
    POST_IMAGE_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tải ảnh bài viết lên hệ thống"),
    POST_VIDEO_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Bài viết chỉ được tải lên tối đa một video"),
    POST_MEDIA_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Bài viết chỉ được tải lên tối đa 4 media"),
    POST_VIDEO_FILE_EMPTY(HttpStatus.BAD_REQUEST, "Video bài viết không được để trống"),
    POST_VIDEO_TOO_LARGE(HttpStatus.BAD_REQUEST, "Video bài viết không được vượt quá 100 MB"),
    POST_VIDEO_EXTENSION_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Định dạng video bài viết không được hỗ trợ"),
    POST_VIDEO_MIME_TYPE_INVALID(HttpStatus.BAD_REQUEST, "MIME type của video bài viết không hợp lệ"),
    POST_VIDEO_SIGNATURE_INVALID(HttpStatus.BAD_REQUEST, "Nội dung tệp video bài viết không hợp lệ"),
    POST_VIDEO_DURATION_EXCEEDED(HttpStatus.BAD_REQUEST, "Video bài viết không được dài quá 3 phút"),
    POST_VIDEO_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tải video bài viết lên hệ thống"),
    POST_MEDIA_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR, "Không thể xóa media bài viết trên hệ thống lưu trữ"),
    POST_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bài viết"),
    POST_NOT_AVAILABLE(HttpStatus.BAD_REQUEST, "Bài viết không khả dụng để thực hiện thao tác này"),
    POST_ALREADY_LIKED(HttpStatus.CONFLICT, "Bạn đã Like bài viết này"),
    POST_NOT_LIKED(HttpStatus.BAD_REQUEST, "Bạn chưa Like bài viết này"),
    POST_FORBIDDEN(HttpStatus.FORBIDDEN, "Bạn không có quyền chỉnh sửa bài viết này"),
    POST_REPOST_SELF_FORBIDDEN(HttpStatus.BAD_REQUEST, "Bạn không thể đăng lại bài viết của chính mình"),
    POST_EDIT_TIME_EXPIRED(HttpStatus.BAD_REQUEST, "Bài viết chỉ được chỉnh sửa trong vòng 15 phút sau khi đăng"),
    POST_CONTENT_REQUIRED(HttpStatus.BAD_REQUEST, "Bài viết sau khi chỉnh sửa phải có nội dung hoặc ít nhất một media"),
    POST_MEDIA_NOT_FOUND(HttpStatus.BAD_REQUEST, "Media cần giữ lại không thuộc bài viết đang chỉnh sửa"),
    LOCATION_PLACE_ID_REQUIRED(HttpStatus.BAD_REQUEST, "Google Place ID của địa điểm là bắt buộc"),
    LOCATION_DISPLAY_NAME_REQUIRED(HttpStatus.BAD_REQUEST, "Tên hiển thị của địa điểm là bắt buộc"),
    LOCATION_COORDINATES_REQUIRED(HttpStatus.BAD_REQUEST, "Vĩ độ và kinh độ của địa điểm là bắt buộc"),
    LOCATION_LATITUDE_INVALID(HttpStatus.BAD_REQUEST, "Vĩ độ phải nằm trong khoảng từ -90 đến 90"),
    LOCATION_LONGITUDE_INVALID(HttpStatus.BAD_REQUEST, "Kinh độ phải nằm trong khoảng từ -180 đến 180"),
    LOCATION_FIELD_TOO_LONG(HttpStatus.BAD_REQUEST, "Thông tin địa điểm vượt quá độ dài cho phép"),
    LOCATION_ACTION_INVALID(HttpStatus.BAD_REQUEST, "Hành động cập nhật địa điểm không hợp lệ"),
    LOCATION_REQUIRED_FOR_REPLACE(HttpStatus.BAD_REQUEST, "Cần cung cấp địa điểm khi thay đổi Location"),
    LOCATION_PAYLOAD_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Không được gửi dữ liệu địa điểm với hành động này"),
    POST_HASHTAG_LIMIT_EXCEEDED(HttpStatus.BAD_REQUEST, "Bài viết chỉ được gắn tối đa 10 hashtag"),
    POST_HASHTAG_TOO_LONG(HttpStatus.BAD_REQUEST, "Mỗi hashtag không được vượt quá 100 ký tự"),
    POST_HASHTAG_INVALID(HttpStatus.BAD_REQUEST, "Hashtag chỉ được chứa chữ, số hoặc dấu gạch dưới"),
    COMMENT_CONTENT_REQUIRED(HttpStatus.BAD_REQUEST, "Nội dung bình luận không được để trống"),
    COMMENT_CONTENT_TOO_LONG(HttpStatus.BAD_REQUEST, "Nội dung bình luận không được vượt quá 1000 ký tự"),
    COMMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bình luận"),
    COMMENT_PARENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bình luận cần trả lời"),
    COMMENT_PARENT_NOT_AVAILABLE(HttpStatus.BAD_REQUEST, "Bình luận này không còn khả dụng để trả lời"),
    COMMENT_REPLY_DEPTH_EXCEEDED(HttpStatus.BAD_REQUEST, "Chỉ được trả lời bình luận tối đa một cấp"),
    COMMENT_FORBIDDEN(HttpStatus.FORBIDDEN, "Bạn không có quyền xóa bình luận này"),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy thông báo"),
    CANNOT_BLOCK_SELF(HttpStatus.BAD_REQUEST, "Bạn không thể chặn chính mình"),
    CANNOT_RESTRICT_SELF(HttpStatus.BAD_REQUEST, "Bạn không thể hạn chế chính mình"),
    USER_RELATIONSHIP_BLOCKED(HttpStatus.FORBIDDEN, "Không thể tương tác do quan hệ chặn giữa hai tài khoản"),
    FOLLOW_SELF_FORBIDDEN(HttpStatus.BAD_REQUEST, "Bạn không thể theo dõi chính mình"),
    FOLLOW_ALREADY_EXISTS(HttpStatus.CONFLICT, "Bạn đã theo dõi người dùng này"),
    FOLLOW_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy quan hệ theo dõi"),
    REPORT_DESCRIPTION_REQUIRED(HttpStatus.BAD_REQUEST, "Mô tả là bắt buộc khi lý do báo cáo là OTHER"),
    REPORT_DESCRIPTION_TOO_LONG(HttpStatus.BAD_REQUEST, "Mô tả báo cáo không được vượt quá 1000 ký tự"),
    REPORT_OWN_POST_FORBIDDEN(HttpStatus.FORBIDDEN, "Bạn không thể báo cáo bài viết của chính mình"),
    REPORT_ALREADY_PENDING(HttpStatus.CONFLICT, "Bạn đã có một báo cáo đang chờ xử lý cho bài viết này"),
    CLOUDINARY_CONFIGURATION_INVALID(HttpStatus.INTERNAL_SERVER_ERROR, "Cấu hình lưu trữ ảnh chưa hợp lệ"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "Bạn cần đăng nhập để tiếp tục"),
    INVALID_ACCESS_TOKEN(HttpStatus.UNAUTHORIZED, "Access Token không hợp lệ"),
    ACCESS_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Access Token đã hết hạn"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy người dùng"),
    USER_BLOCKED(HttpStatus.FORBIDDEN, "Tài khoản đã bị khóa"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "Bạn không có quyền thực hiện thao tác này"),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED, "Phương thức HTTP không được hỗ trợ cho API này"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy dữ liệu"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Hệ thống đang gặp lỗi, vui lòng thử lại sau");

    private final HttpStatus httpStatus;
    private final String defaultMessage;

    ErrorCode(HttpStatus httpStatus, String defaultMessage) {
        this.httpStatus = httpStatus;
        this.defaultMessage = defaultMessage;
    }

    public HttpStatus getHttpStatus() {
        return httpStatus;
    }

    public String getDefaultMessage() {
        return defaultMessage;
    }
}
