package com.stu.edu.vn.backend.admin.notification.enums;

/** Nhóm sự kiện vận hành được hiển thị trong Notification Center của ADMIN. */
public enum AdminNotificationType {
    POST_REPORT_CREATED,
    PROFILE_REPORT_CREATED,
    MODERATION_SUGGESTION_CREATED,
    MODERATION_SUGGESTION_ACCEPTED,
    MODERATION_SUGGESTION_REJECTED,
    USER_AUTO_BLOCKED_REPEATED_VIOLATION,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_PROFILE_UPDATED_BY_ADMIN,
    POST_HIDDEN_BY_ADMIN,
    POST_RESTORED_BY_ADMIN,
    HASHTAG_CREATED,
    HASHTAG_UPDATED,
    HASHTAG_DELETED,
    ADMIN_CREATED,
    ADMIN_UPDATED,
    ADMIN_DISABLED,
    ADMIN_ENABLED,
    ADMIN_PASSWORD_RESET,
    ADMIN_ROLE_ASSIGNED,
    ADMIN_ROLE_REVOKED,
    ADMIN_ROLE_CREATED,
    ADMIN_ROLE_PERMISSIONS_UPDATED
}
