const AUTH_BASE = '/api/v1/auth';
const AUTH_PROVIDERS_BASE = '/api/v1/users/me/auth-providers';
const USER_ONBOARDING_BASE = '/api/v1/users/me/onboarding';
const ACADEMIC_BASE = '/api/v1/academic';

// CÃ¡c path dÆ°á»›i Ä‘Ã¢y Ä‘Æ°á»£c Ä‘á»‘i chiáº¿u trá»±c tiáº¿p vá»›i AuthController hiá»‡n hÃ nh.
export const AUTH_ENDPOINTS = Object.freeze({
  registrations: `${AUTH_BASE}/registrations`,
  verifyRegistration: `${AUTH_BASE}/registrations/verify`,
  resendRegistration: `${AUTH_BASE}/registrations/resend`,
  registrationStatus: `${AUTH_BASE}/registrations/status`,
  cancelRegistration: `${AUTH_BASE}/registrations/cancel`,
  login: `${AUTH_BASE}/login`,
  passwordRecovery: `${AUTH_BASE}/password-recovery`,
  verifyPasswordRecovery: `${AUTH_BASE}/password-recovery/verify`,
  resendPasswordRecovery: `${AUTH_BASE}/password-recovery/resend`,
  completePasswordRecovery: `${AUTH_BASE}/password-recovery/complete`,
  googleAuth: `${AUTH_BASE}/oauth/google`,
  facebookAuth: `${AUTH_BASE}/oauth/facebook`,
  resolveSocialConflict: `${AUTH_BASE}/registrations/resolve-social-conflict`,
  refreshToken: `${AUTH_BASE}/refresh-token`,
  logout: `${AUTH_BASE}/logout`,
  reauthenticate: `${AUTH_BASE}/reauthenticate`,
  authProviders: AUTH_PROVIDERS_BASE,
  linkEmail: `${AUTH_PROVIDERS_BASE}/email`,
  verifyLinkedEmail: `${AUTH_PROVIDERS_BASE}/email/verify`,
  completeLinkedEmail: `${AUTH_PROVIDERS_BASE}/email/complete`,
  resendLinkedEmail: `${AUTH_PROVIDERS_BASE}/email/resend`,
  password: `${AUTH_PROVIDERS_BASE}/password`,
  linkGoogle: `${AUTH_PROVIDERS_BASE}/google`,
  linkFacebook: `${AUTH_PROVIDERS_BASE}/facebook`,
  unlinkProvider: (provider) => `${AUTH_PROVIDERS_BASE}/${encodeURIComponent(provider)}`,
});

export const USER_ENDPOINTS = Object.freeze({
  onboarding: USER_ONBOARDING_BASE,
  usernameAvailability: `${USER_ONBOARDING_BASE}/username-availability`,
  profile: '/api/v1/users/me/profile',
  publicProfile: (userId) => `/api/v1/users/${encodeURIComponent(userId)}`,
  avatar: '/api/v1/users/me/avatar',
  follow: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/follow`,
  followers: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/followers`,
  following: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/following`,
  block: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/block`,
  blockedUsers: '/api/v1/users/me/blocked-users',
  restriction: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/restriction`,
  restrictedUsers: '/api/v1/users/me/restricted-users',
  profileReports: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/profile-reports`,
  posts: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/posts`,
  reposts: (userId) => `/api/v1/users/${encodeURIComponent(userId)}/reposts`,
});

export const ACADEMIC_ENDPOINTS = Object.freeze({
  schools: `${ACADEMIC_BASE}/schools`,
  faculties: (schoolId) => `${ACADEMIC_BASE}/schools/${encodeURIComponent(schoolId)}/faculties`,
  majors: (facultyId) => `${ACADEMIC_BASE}/faculties/${encodeURIComponent(facultyId)}/majors`,
  interests: '/api/v1/interests',
});

export const POST_ENDPOINTS = Object.freeze({
  root: '/api/v1/posts',
  saved: '/api/v1/posts/saved',
  liked: '/api/v1/posts/liked',
  detail: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}`,
  likes: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}/likes`,
  saves: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}/saves`,
  repost: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}/repost`,
  reports: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}/reports`,
  comments: (postId) => `/api/v1/posts/${encodeURIComponent(postId)}/comments`,
  replies: (commentId) => `/api/v1/comments/${encodeURIComponent(commentId)}/replies`,
  comment: (commentId) => `/api/v1/comments/${encodeURIComponent(commentId)}`,
  hashtagSuggestions: '/api/v1/hashtags/suggestions',
});

export const DISCOVERY_ENDPOINTS = Object.freeze({
  feedForYou: '/api/v1/feeds/for-you',
  feedFollowing: '/api/v1/feeds/following',
  nearby: '/api/v1/discovery/nearby',
  mapLocations: '/api/v1/discovery/map/locations',
  mapLocationPosts: (locationId) => `/api/v1/discovery/map/locations/${encodeURIComponent(locationId)}/posts`,
  studentRecommendations: '/api/v1/recommendations/students',
  searchUsers: '/api/v1/search/users',
  searchPosts: '/api/v1/search/posts',
  notifications: '/api/v1/notifications',
  notificationUnreadCount: '/api/v1/notifications/unread-count',
  notificationReadAll: '/api/v1/notifications/read-all',
  notificationRead: (notificationId) => `/api/v1/notifications/${encodeURIComponent(notificationId)}/read`,
  notification: (notificationId) => `/api/v1/notifications/${encodeURIComponent(notificationId)}`,
});

export const ADMIN_ENDPOINTS = Object.freeze({
  profile: '/api/v1/admin/profile',
  profilePassword: '/api/v1/admin/profile/password',
  admins: '/api/v1/admin/admins',
  admin: (adminId) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}`,
  disableAdmin: (adminId) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}/disable`,
  enableAdmin: (adminId) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}/enable`,
  resetAdminPassword: (adminId) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}/password`,
  adminRole: (adminId, roleCode) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}/roles/${encodeURIComponent(roleCode)}`,
  revokeAdminRole: (adminId, roleCode) => `/api/v1/admin/admins/${encodeURIComponent(adminId)}/roles/${encodeURIComponent(roleCode)}/revoke`,
  adminRoleCatalog: '/api/v1/admin/admins/roles/catalog',
  adminRoles: '/api/v1/admin/roles',
  createAdminRole: '/api/v1/admin/roles',
  adminPermissions: '/api/v1/admin/roles/permissions',
  rolePermissions: (roleCode) => `/api/v1/admin/roles/${encodeURIComponent(roleCode)}/permissions`,
  users: '/api/v1/admin/users',
  user: (userId) => `/api/v1/admin/users/${encodeURIComponent(userId)}`,
  userProfile: (userId) => `/api/v1/admin/users/${encodeURIComponent(userId)}/profile`,
  blockUser: (userId) => `/api/v1/admin/users/${encodeURIComponent(userId)}/block`,
  unblockUser: (userId) => `/api/v1/admin/users/${encodeURIComponent(userId)}/unblock`,
  posts: '/api/v1/admin/posts',
  hashtags: '/api/v1/admin/hashtags',
  hashtag: (hashtagId) => `/api/v1/admin/hashtags/${encodeURIComponent(hashtagId)}`,
  academicSchools: '/api/v1/admin/academic/schools',
  academicSchool: (schoolId) => `/api/v1/admin/academic/schools/${encodeURIComponent(schoolId)}`,
  academicSchoolStatus: (schoolId) => `/api/v1/admin/academic/schools/${encodeURIComponent(schoolId)}/status`,
  academicFaculties: (schoolId) => `/api/v1/admin/academic/schools/${encodeURIComponent(schoolId)}/faculties`,
  academicFaculty: (facultyId) => `/api/v1/admin/academic/faculties/${encodeURIComponent(facultyId)}`,
  academicFacultyStatus: (facultyId) => `/api/v1/admin/academic/faculties/${encodeURIComponent(facultyId)}/status`,
  academicMajors: (facultyId) => `/api/v1/admin/academic/faculties/${encodeURIComponent(facultyId)}/majors`,
  academicMajor: (majorId) => `/api/v1/admin/academic/majors/${encodeURIComponent(majorId)}`,
  academicMajorStatus: (majorId) => `/api/v1/admin/academic/majors/${encodeURIComponent(majorId)}/status`,
  academicInterests: '/api/v1/admin/academic/interests',
  academicInterest: (interestId) => `/api/v1/admin/academic/interests/${encodeURIComponent(interestId)}`,
  academicInterestStatus: (interestId) => `/api/v1/admin/academic/interests/${encodeURIComponent(interestId)}/status`,
  post: (postId) => `/api/v1/admin/posts/${encodeURIComponent(postId)}`,
  hidePost: (postId) => `/api/v1/admin/posts/${encodeURIComponent(postId)}/hide`,
  restorePost: (postId) => `/api/v1/admin/posts/${encodeURIComponent(postId)}/restore`,
  moderationCases: '/api/v1/admin/moderation-cases',
  moderationCase: (caseId) => `/api/v1/admin/moderation-cases/${encodeURIComponent(caseId)}`,
  resolveCaseNoViolation: (caseId) => `/api/v1/admin/moderation-cases/${encodeURIComponent(caseId)}/resolve-no-violation`,
  resolveCaseAction: (caseId) => `/api/v1/admin/moderation-cases/${encodeURIComponent(caseId)}/resolve-action`,
  profileReports: '/api/v1/admin/profile-reports',
  profileReport: (caseId) => `/api/v1/admin/profile-reports/${encodeURIComponent(caseId)}`,
  rejectProfileReport: (caseId) => `/api/v1/admin/profile-reports/${encodeURIComponent(caseId)}/reject`,
  resolveProfileReport: (caseId) => `/api/v1/admin/profile-reports/${encodeURIComponent(caseId)}/resolve`,
  actions: '/api/v1/admin/actions',
  action: (actionId) => `/api/v1/admin/actions/${encodeURIComponent(actionId)}`,
  userEngagementMonthly: '/api/v1/admin/analytics/user-engagement/monthly',
  userEngagementSummary: '/api/v1/admin/analytics/user-engagement/summary',
  userEngagementDashboard: '/api/v1/admin/analytics/user-engagement/dashboard',
  postAnalytics: '/api/v1/admin/analytics/posts',
  hashtagAnalytics: '/api/v1/admin/analytics/hashtags',
});

const COLLABORATOR_BASE = '/api/v1/admin/collaborator';
export const COLLABORATOR_ENDPOINTS = Object.freeze({
  identity: `${COLLABORATOR_BASE}/social-identity`,
  dashboard: `${COLLABORATOR_BASE}/dashboard`,
  posts: `${COLLABORATOR_BASE}/posts`,
  post: (postId) => `${COLLABORATOR_BASE}/posts/${encodeURIComponent(postId)}`,
  analytics: (postId) => `${COLLABORATOR_BASE}/posts/${encodeURIComponent(postId)}/analytics`,
  hashtags: `${COLLABORATOR_BASE}/hashtags`,
  like: (postId) => `${COLLABORATOR_BASE}/posts/${encodeURIComponent(postId)}/like`,
  comments: (postId) => `${COLLABORATOR_BASE}/posts/${encodeURIComponent(postId)}/comments`,
  replies: (commentId) => `${COLLABORATOR_BASE}/comments/${encodeURIComponent(commentId)}/replies`,
  repost: (postId) => `${COLLABORATOR_BASE}/posts/${encodeURIComponent(postId)}/repost`,
});
