-- Đồng bộ audit cho chức năng quản trị viên tự cập nhật hồ sơ và đổi mật khẩu.
ALTER TABLE admin_actions
    MODIFY COLUMN action_type ENUM(
        'BLOCK_USER','UNBLOCK_USER','UPDATE_USER_PROFILE','CREATE_HASHTAG','UPDATE_HASHTAG','DELETE_HASHTAG',
        'HIDE_POST','RESTORE_POST','RESOLVE_REPORT','REJECT_REPORT','RESOLVE_MODERATION_CASE',
        'REJECT_MODERATION_CASE','RESOLVE_PROFILE_REPORT','REJECT_PROFILE_REPORT','CREATE_ADMIN','UPDATE_ADMIN',
        'UPDATE_ADMIN_PROFILE','DISABLE_ADMIN','ENABLE_ADMIN','RESET_ADMIN_PASSWORD','CHANGE_ADMIN_PASSWORD',
        'ASSIGN_ADMIN_ROLE','REVOKE_ADMIN_ROLE','CREATE_ADMIN_ROLE','UPDATE_ROLE_PERMISSIONS'
    ) NOT NULL;
