-- Bổ sung action audit cho chức năng tạo role quản trị tùy chỉnh.
-- Bảng roles hiện tại đã hỗ trợ role động nên không cần thay đổi cột hoặc khóa.
ALTER TABLE `admin_actions`
  MODIFY `action_type` enum(
    'BLOCK_USER','UNBLOCK_USER','UPDATE_USER_PROFILE','CREATE_HASHTAG','UPDATE_HASHTAG','DELETE_HASHTAG',
    'HIDE_POST','RESTORE_POST','RESOLVE_REPORT','REJECT_REPORT','RESOLVE_MODERATION_CASE',
    'REJECT_MODERATION_CASE','RESOLVE_PROFILE_REPORT','REJECT_PROFILE_REPORT','CREATE_ADMIN','UPDATE_ADMIN',
    'DISABLE_ADMIN','ENABLE_ADMIN','RESET_ADMIN_PASSWORD','ASSIGN_ADMIN_ROLE','REVOKE_ADMIN_ROLE',
    'CREATE_ADMIN_ROLE','UPDATE_ROLE_PERMISSIONS'
  ) NOT NULL;
