package com.stu.edu.vn.backend.admin.enums;

/**
 * Loại thao tác quản trị, ánh xạ đầy đủ các giá trị ENUM hiện có của bảng admin_actions.
 */
public enum AdminActionType {
    BLOCK_USER,
    UNBLOCK_USER,
    UPDATE_USER_PROFILE,
    CREATE_HASHTAG,
    UPDATE_HASHTAG,
    DELETE_HASHTAG,
    HIDE_POST,
    RESTORE_POST,
    RESOLVE_REPORT,
    REJECT_REPORT,
    RESOLVE_MODERATION_CASE,
    REJECT_MODERATION_CASE,
    RESOLVE_PROFILE_REPORT,
    REJECT_PROFILE_REPORT,
    CREATE_ADMIN,
    UPDATE_ADMIN,
    UPDATE_ADMIN_PROFILE,
    DISABLE_ADMIN,
    ENABLE_ADMIN,
    RESET_ADMIN_PASSWORD,
    CHANGE_ADMIN_PASSWORD,
    ASSIGN_ADMIN_ROLE,
    REVOKE_ADMIN_ROLE,
    CREATE_ADMIN_ROLE,
    UPDATE_ROLE_PERMISSIONS,
    CREATE_MANAGED_SOCIAL_IDENTITY,
    DISABLE_MANAGED_SOCIAL_IDENTITY,
    COLLABORATOR_POST_CREATED,
    COLLABORATOR_POST_UPDATED,
    COLLABORATOR_POST_DELETED,
    MODERATION_SUGGESTION_CREATED,
    MODERATION_SUGGESTION_ACCEPTED,
    MODERATION_SUGGESTION_REJECTED
}
