-- Cho phép lịch sử quản trị ghi nhận đầy đủ thao tác tạo và xóa hashtag.
ALTER TABLE admin_actions
    MODIFY COLUMN action_type ENUM(
        'BLOCK_USER', 'UNBLOCK_USER', 'UPDATE_USER_PROFILE',
        'CREATE_HASHTAG', 'DELETE_HASHTAG',
        'HIDE_POST', 'RESTORE_POST', 'RESOLVE_REPORT', 'REJECT_REPORT',
        'RESOLVE_MODERATION_CASE', 'REJECT_MODERATION_CASE',
        'RESOLVE_PROFILE_REPORT', 'REJECT_PROFILE_REPORT'
    ) NOT NULL,
    MODIFY COLUMN target_type ENUM(
        'USER', 'POST', 'HASHTAG', 'REPORT', 'MODERATION_CASE', 'PROFILE_REPORT'
    ) NOT NULL;
