export const SOCIAL_CONFLICT_TYPES = Object.freeze({
  PENDING_EMAIL_MISMATCH: 'PENDING_EMAIL_MISMATCH',
  ACTIVE_EMAIL_MATCH_UNLINKED_PROVIDER: 'ACTIVE_EMAIL_MATCH_UNLINKED_PROVIDER',
});

export const SOCIAL_CONFLICT_ACTIONS = Object.freeze({
  CONTINUE_OTP: 'CONTINUE_OTP',
  CANCEL_PENDING_AND_CONTINUE_SOCIAL: 'CANCEL_PENDING_AND_CONTINUE_SOCIAL',
  LOGIN_EXISTING_ACCOUNT: 'LOGIN_EXISTING_ACCOUNT',
  START_ACCOUNT_RECOVERY: 'START_ACCOUNT_RECOVERY',
  CONTINUE_WITH_SEPARATE_ACCOUNT: 'CONTINUE_WITH_SEPARATE_ACCOUNT',
});

const ACTIONS_BY_TYPE = Object.freeze({
  [SOCIAL_CONFLICT_TYPES.PENDING_EMAIL_MISMATCH]: Object.freeze([
    SOCIAL_CONFLICT_ACTIONS.CONTINUE_OTP,
    SOCIAL_CONFLICT_ACTIONS.CANCEL_PENDING_AND_CONTINUE_SOCIAL,
  ]),
  [SOCIAL_CONFLICT_TYPES.ACTIVE_EMAIL_MATCH_UNLINKED_PROVIDER]: Object.freeze([
    SOCIAL_CONFLICT_ACTIONS.LOGIN_EXISTING_ACCOUNT,
    SOCIAL_CONFLICT_ACTIONS.START_ACCOUNT_RECOVERY,
    SOCIAL_CONFLICT_ACTIONS.CONTINUE_WITH_SEPARATE_ACCOUNT,
  ]),
});

export function allowedSocialConflictActions(conflictType, provider) {
  const actions = ACTIONS_BY_TYPE[conflictType] ?? [];
  if (conflictType !== SOCIAL_CONFLICT_TYPES.ACTIVE_EMAIL_MATCH_UNLINKED_PROVIDER) return actions;
  return provider === 'FACEBOOK'
    ? actions.filter((action) => action !== SOCIAL_CONFLICT_ACTIONS.START_ACCOUNT_RECOVERY)
    : actions.filter((action) => action !== SOCIAL_CONFLICT_ACTIONS.CONTINUE_WITH_SEPARATE_ACCOUNT);
}
