export const PASSWORD_RECOVERY_STEP = Object.freeze({
  IDENTIFIER: 'IDENTIFIER',
  NOTICE: 'NOTICE',
  OTP: 'OTP',
  RESET: 'RESET',
});

export const PASSWORD_POLICY = Object.freeze({ minLength: 8, maxLength: 72 });

export const TERMINAL_RECOVERY_CODES = new Set([
  'AUTH_PASSWORD_RECOVERY_FLOW_INVALID',
  'AUTH_PASSWORD_RECOVERY_FLOW_EXPIRED',
  'AUTH_PASSWORD_RECOVERY_FLOW_ALREADY_USED',
  'AUTH_PASSWORD_RECOVERY_OTP_EXPIRED',
  'AUTH_PASSWORD_RECOVERY_OTP_ATTEMPTS_EXCEEDED',
]);

export const TERMINAL_RESET_CODES = new Set([
  'AUTH_PASSWORD_RESET_TOKEN_INVALID',
  'AUTH_PASSWORD_RESET_TOKEN_EXPIRED',
  'AUTH_PASSWORD_RESET_TOKEN_USED',
]);
